//
// Copyright Miro Knejp 2021.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE.txt or copy at https://www.boost.org/LICENSE_1_0.txt)
//

namespace dotVariant
{
    /// <summary>
    /// Overload selectors for <c>GetUnsafe()</c> direct access.
    /// </summary>
    public static class Accessor
    {
        public readonly struct _1 { public static readonly _1 Default; }
        public readonly struct _2 { public static readonly _2 Default; }
        public readonly struct _3 { public static readonly _3 Default; }
        public readonly struct _4 { public static readonly _4 Default; }
        public readonly struct _5 { public static readonly _5 Default; }
        public readonly struct _6 { public static readonly _6 Default; }
        public readonly struct _7 { public static readonly _7 Default; }
        public readonly struct _8 { public static readonly _8 Default; }
        public readonly struct _9 { public static readonly _9 Default; }
        public readonly struct _10 { public static readonly _10 Default; }
        public readonly struct _11 { public static readonly _11 Default; }
        public readonly struct _12 { public static readonly _12 Default; }
        public readonly struct _13 { public static readonly _13 Default; }
        public readonly struct _14 { public static readonly _14 Default; }
        public readonly struct _15 { public static readonly _15 Default; }
        public readonly struct _16 { public static readonly _16 Default; }
        public readonly struct _17 { public static readonly _17 Default; }
        public readonly struct _18 { public static readonly _18 Default; }
        public readonly struct _19 { public static readonly _19 Default; }
        public readonly struct _20 { public static readonly _20 Default; }
        public readonly struct _21 { public static readonly _21 Default; }
        public readonly struct _22 { public static readonly _22 Default; }
        public readonly struct _23 { public static readonly _23 Default; }
        public readonly struct _24 { public static readonly _24 Default; }
        public readonly struct _25 { public static readonly _25 Default; }
        public readonly struct _26 { public static readonly _26 Default; }
        public readonly struct _27 { public static readonly _27 Default; }
        public readonly struct _28 { public static readonly _28 Default; }
        public readonly struct _29 { public static readonly _29 Default; }
        public readonly struct _30 { public static readonly _30 Default; }
        public readonly struct _31 { public static readonly _31 Default; }
        public readonly struct _32 { public static readonly _32 Default; }
        public readonly struct _33 { public static readonly _33 Default; }
        public readonly struct _34 { public static readonly _34 Default; }
        public readonly struct _35 { public static readonly _35 Default; }
        public readonly struct _36 { public static readonly _36 Default; }
        public readonly struct _37 { public static readonly _37 Default; }
        public readonly struct _38 { public static readonly _38 Default; }
        public readonly struct _39 { public static readonly _39 Default; }
        public readonly struct _40 { public static readonly _40 Default; }
        public readonly struct _41 { public static readonly _41 Default; }
        public readonly struct _42 { public static readonly _42 Default; }
        public readonly struct _43 { public static readonly _43 Default; }
        public readonly struct _44 { public static readonly _44 Default; }
        public readonly struct _45 { public static readonly _45 Default; }
        public readonly struct _46 { public static readonly _46 Default; }
        public readonly struct _47 { public static readonly _47 Default; }
        public readonly struct _48 { public static readonly _48 Default; }
        public readonly struct _49 { public static readonly _49 Default; }
        public readonly struct _50 { public static readonly _50 Default; }
        public readonly struct _51 { public static readonly _51 Default; }
        public readonly struct _52 { public static readonly _52 Default; }
        public readonly struct _53 { public static readonly _53 Default; }
        public readonly struct _54 { public static readonly _54 Default; }
        public readonly struct _55 { public static readonly _55 Default; }
        public readonly struct _56 { public static readonly _56 Default; }
        public readonly struct _57 { public static readonly _57 Default; }
        public readonly struct _58 { public static readonly _58 Default; }
        public readonly struct _59 { public static readonly _59 Default; }
        public readonly struct _60 { public static readonly _60 Default; }
        public readonly struct _61 { public static readonly _61 Default; }
        public readonly struct _62 { public static readonly _62 Default; }
        public readonly struct _63 { public static readonly _63 Default; }
        public readonly struct _64 { public static readonly _64 Default; }
        public readonly struct _65 { public static readonly _65 Default; }
        public readonly struct _66 { public static readonly _66 Default; }
        public readonly struct _67 { public static readonly _67 Default; }
        public readonly struct _68 { public static readonly _68 Default; }
        public readonly struct _69 { public static readonly _69 Default; }
        public readonly struct _70 { public static readonly _70 Default; }
        public readonly struct _71 { public static readonly _71 Default; }
        public readonly struct _72 { public static readonly _72 Default; }
        public readonly struct _73 { public static readonly _73 Default; }
        public readonly struct _74 { public static readonly _74 Default; }
        public readonly struct _75 { public static readonly _75 Default; }
        public readonly struct _76 { public static readonly _76 Default; }
        public readonly struct _77 { public static readonly _77 Default; }
        public readonly struct _78 { public static readonly _78 Default; }
        public readonly struct _79 { public static readonly _79 Default; }
        public readonly struct _80 { public static readonly _80 Default; }
        public readonly struct _81 { public static readonly _81 Default; }
        public readonly struct _82 { public static readonly _82 Default; }
        public readonly struct _83 { public static readonly _83 Default; }
        public readonly struct _84 { public static readonly _84 Default; }
        public readonly struct _85 { public static readonly _85 Default; }
        public readonly struct _86 { public static readonly _86 Default; }
        public readonly struct _87 { public static readonly _87 Default; }
        public readonly struct _88 { public static readonly _88 Default; }
        public readonly struct _89 { public static readonly _89 Default; }
        public readonly struct _90 { public static readonly _90 Default; }
        public readonly struct _91 { public static readonly _91 Default; }
        public readonly struct _92 { public static readonly _92 Default; }
        public readonly struct _93 { public static readonly _93 Default; }
        public readonly struct _94 { public static readonly _94 Default; }
        public readonly struct _95 { public static readonly _95 Default; }
        public readonly struct _96 { public static readonly _96 Default; }
        public readonly struct _97 { public static readonly _97 Default; }
        public readonly struct _98 { public static readonly _98 Default; }
        public readonly struct _99 { public static readonly _99 Default; }
        public readonly struct _100 { public static readonly _100 Default; }
        public readonly struct _101 { public static readonly _101 Default; }
        public readonly struct _102 { public static readonly _102 Default; }
        public readonly struct _103 { public static readonly _103 Default; }
        public readonly struct _104 { public static readonly _104 Default; }
        public readonly struct _105 { public static readonly _105 Default; }
        public readonly struct _106 { public static readonly _106 Default; }
        public readonly struct _107 { public static readonly _107 Default; }
        public readonly struct _108 { public static readonly _108 Default; }
        public readonly struct _109 { public static readonly _109 Default; }
        public readonly struct _110 { public static readonly _110 Default; }
        public readonly struct _111 { public static readonly _111 Default; }
        public readonly struct _112 { public static readonly _112 Default; }
        public readonly struct _113 { public static readonly _113 Default; }
        public readonly struct _114 { public static readonly _114 Default; }
        public readonly struct _115 { public static readonly _115 Default; }
        public readonly struct _116 { public static readonly _116 Default; }
        public readonly struct _117 { public static readonly _117 Default; }
        public readonly struct _118 { public static readonly _118 Default; }
        public readonly struct _119 { public static readonly _119 Default; }
        public readonly struct _120 { public static readonly _120 Default; }
        public readonly struct _121 { public static readonly _121 Default; }
        public readonly struct _122 { public static readonly _122 Default; }
        public readonly struct _123 { public static readonly _123 Default; }
        public readonly struct _124 { public static readonly _124 Default; }
        public readonly struct _125 { public static readonly _125 Default; }
        public readonly struct _126 { public static readonly _126 Default; }
        public readonly struct _127 { public static readonly _127 Default; }
        public readonly struct _128 { public static readonly _128 Default; }
        public readonly struct _129 { public static readonly _129 Default; }
        public readonly struct _130 { public static readonly _130 Default; }
        public readonly struct _131 { public static readonly _131 Default; }
        public readonly struct _132 { public static readonly _132 Default; }
        public readonly struct _133 { public static readonly _133 Default; }
        public readonly struct _134 { public static readonly _134 Default; }
        public readonly struct _135 { public static readonly _135 Default; }
        public readonly struct _136 { public static readonly _136 Default; }
        public readonly struct _137 { public static readonly _137 Default; }
        public readonly struct _138 { public static readonly _138 Default; }
        public readonly struct _139 { public static readonly _139 Default; }
        public readonly struct _140 { public static readonly _140 Default; }
        public readonly struct _141 { public static readonly _141 Default; }
        public readonly struct _142 { public static readonly _142 Default; }
        public readonly struct _143 { public static readonly _143 Default; }
        public readonly struct _144 { public static readonly _144 Default; }
        public readonly struct _145 { public static readonly _145 Default; }
        public readonly struct _146 { public static readonly _146 Default; }
        public readonly struct _147 { public static readonly _147 Default; }
        public readonly struct _148 { public static readonly _148 Default; }
        public readonly struct _149 { public static readonly _149 Default; }
        public readonly struct _150 { public static readonly _150 Default; }
        public readonly struct _151 { public static readonly _151 Default; }
        public readonly struct _152 { public static readonly _152 Default; }
        public readonly struct _153 { public static readonly _153 Default; }
        public readonly struct _154 { public static readonly _154 Default; }
        public readonly struct _155 { public static readonly _155 Default; }
        public readonly struct _156 { public static readonly _156 Default; }
        public readonly struct _157 { public static readonly _157 Default; }
        public readonly struct _158 { public static readonly _158 Default; }
        public readonly struct _159 { public static readonly _159 Default; }
        public readonly struct _160 { public static readonly _160 Default; }
        public readonly struct _161 { public static readonly _161 Default; }
        public readonly struct _162 { public static readonly _162 Default; }
        public readonly struct _163 { public static readonly _163 Default; }
        public readonly struct _164 { public static readonly _164 Default; }
        public readonly struct _165 { public static readonly _165 Default; }
        public readonly struct _166 { public static readonly _166 Default; }
        public readonly struct _167 { public static readonly _167 Default; }
        public readonly struct _168 { public static readonly _168 Default; }
        public readonly struct _169 { public static readonly _169 Default; }
        public readonly struct _170 { public static readonly _170 Default; }
        public readonly struct _171 { public static readonly _171 Default; }
        public readonly struct _172 { public static readonly _172 Default; }
        public readonly struct _173 { public static readonly _173 Default; }
        public readonly struct _174 { public static readonly _174 Default; }
        public readonly struct _175 { public static readonly _175 Default; }
        public readonly struct _176 { public static readonly _176 Default; }
        public readonly struct _177 { public static readonly _177 Default; }
        public readonly struct _178 { public static readonly _178 Default; }
        public readonly struct _179 { public static readonly _179 Default; }
        public readonly struct _180 { public static readonly _180 Default; }
        public readonly struct _181 { public static readonly _181 Default; }
        public readonly struct _182 { public static readonly _182 Default; }
        public readonly struct _183 { public static readonly _183 Default; }
        public readonly struct _184 { public static readonly _184 Default; }
        public readonly struct _185 { public static readonly _185 Default; }
        public readonly struct _186 { public static readonly _186 Default; }
        public readonly struct _187 { public static readonly _187 Default; }
        public readonly struct _188 { public static readonly _188 Default; }
        public readonly struct _189 { public static readonly _189 Default; }
        public readonly struct _190 { public static readonly _190 Default; }
        public readonly struct _191 { public static readonly _191 Default; }
        public readonly struct _192 { public static readonly _192 Default; }
        public readonly struct _193 { public static readonly _193 Default; }
        public readonly struct _194 { public static readonly _194 Default; }
        public readonly struct _195 { public static readonly _195 Default; }
        public readonly struct _196 { public static readonly _196 Default; }
        public readonly struct _197 { public static readonly _197 Default; }
        public readonly struct _198 { public static readonly _198 Default; }
        public readonly struct _199 { public static readonly _199 Default; }
        public readonly struct _200 { public static readonly _200 Default; }
        public readonly struct _201 { public static readonly _201 Default; }
        public readonly struct _202 { public static readonly _202 Default; }
        public readonly struct _203 { public static readonly _203 Default; }
        public readonly struct _204 { public static readonly _204 Default; }
        public readonly struct _205 { public static readonly _205 Default; }
        public readonly struct _206 { public static readonly _206 Default; }
        public readonly struct _207 { public static readonly _207 Default; }
        public readonly struct _208 { public static readonly _208 Default; }
        public readonly struct _209 { public static readonly _209 Default; }
        public readonly struct _210 { public static readonly _210 Default; }
        public readonly struct _211 { public static readonly _211 Default; }
        public readonly struct _212 { public static readonly _212 Default; }
        public readonly struct _213 { public static readonly _213 Default; }
        public readonly struct _214 { public static readonly _214 Default; }
        public readonly struct _215 { public static readonly _215 Default; }
        public readonly struct _216 { public static readonly _216 Default; }
        public readonly struct _217 { public static readonly _217 Default; }
        public readonly struct _218 { public static readonly _218 Default; }
        public readonly struct _219 { public static readonly _219 Default; }
        public readonly struct _220 { public static readonly _220 Default; }
        public readonly struct _221 { public static readonly _221 Default; }
        public readonly struct _222 { public static readonly _222 Default; }
        public readonly struct _223 { public static readonly _223 Default; }
        public readonly struct _224 { public static readonly _224 Default; }
        public readonly struct _225 { public static readonly _225 Default; }
        public readonly struct _226 { public static readonly _226 Default; }
        public readonly struct _227 { public static readonly _227 Default; }
        public readonly struct _228 { public static readonly _228 Default; }
        public readonly struct _229 { public static readonly _229 Default; }
        public readonly struct _230 { public static readonly _230 Default; }
        public readonly struct _231 { public static readonly _231 Default; }
        public readonly struct _232 { public static readonly _232 Default; }
        public readonly struct _233 { public static readonly _233 Default; }
        public readonly struct _234 { public static readonly _234 Default; }
        public readonly struct _235 { public static readonly _235 Default; }
        public readonly struct _236 { public static readonly _236 Default; }
        public readonly struct _237 { public static readonly _237 Default; }
        public readonly struct _238 { public static readonly _238 Default; }
        public readonly struct _239 { public static readonly _239 Default; }
        public readonly struct _240 { public static readonly _240 Default; }
        public readonly struct _241 { public static readonly _241 Default; }
        public readonly struct _242 { public static readonly _242 Default; }
        public readonly struct _243 { public static readonly _243 Default; }
        public readonly struct _244 { public static readonly _244 Default; }
        public readonly struct _245 { public static readonly _245 Default; }
        public readonly struct _246 { public static readonly _246 Default; }
        public readonly struct _247 { public static readonly _247 Default; }
        public readonly struct _248 { public static readonly _248 Default; }
        public readonly struct _249 { public static readonly _249 Default; }
        public readonly struct _250 { public static readonly _250 Default; }
        public readonly struct _251 { public static readonly _251 Default; }
        public readonly struct _252 { public static readonly _252 Default; }
        public readonly struct _253 { public static readonly _253 Default; }
        public readonly struct _254 { public static readonly _254 Default; }
        public readonly struct _255 { public static readonly _255 Default; }
    }
}
