# SPDX-FileCopyrightText: 2021 The dotVariant Authors
#
# SPDX-License-Identifier: BSL-1.0

# Read the version number from the tag, build the package in release
# configuration and embed third party licenses.
name: publish
on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: pwsh
    working-directory: src

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dotnet-project-licenses
        run: |
          dotnet tool install --global dotnet-project-licenses

      - name: Build package
        run: |
          if ("${{ github.ref }}" -match "^refs/tags/v(.+)") {
            $version = $Matches[1]
            dotnet build dotVariant/dotVariant.csproj -p:Configuration=Release -p:Version=$version -p:PackageThirdPartyLicenses=true
          } else {
            echo "::error::Unexpected tag format '${ github.refs }}'"
            exit 1
          }

      - name: Upload package
        run: dotnet nuget push dotVariant/bin/Release/dotVariant.*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
