# intentionally broken license header

# Make sure all files are properly attributed with copyright and license
name: reuse
on: pull_request

defaults:
  run:
    shell: pwsh

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install reuse-lint
        run: |
          sudo apt-get install -y "reuse"

      - name: Run reuse-lint
        run: |
          reuse lint