name: continuous test
on: [push, pull_request]

defaults:
  run:
    shell: pwsh
    working-directory: src

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v2

      - run: |
          Get-Item Env:
          dotnet test dotVariant.sln -p:Configuration=${{ matrix.config }}
